# netlify.toml
[build]
  command = "npm run build-client"  # Update to the correct build command for the client
  functions = "server/functions"
  publish = "client/build"   # Update to the correct publish directory for the client

[dev]
  publish = "client/build"
  functions = "server/functions"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200